---
title: "RWorksheet_Quillo#3a"
author: "Carl"
date: "2023-10-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = TRUE}
#1a

dfRespondents <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
dfSex <- c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
dfFathersOcc <- c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
dfPersonatHome <- c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
dfSiblingsatSch <- c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
dfTypesofHouses <- c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)

dfHouseholdData <- data.frame("Respondents" = dfRespondents,
                              "Sex" = dfSex,
                              "Fathers Occupation" = dfFathersOcc,
                              "Persons at Home" = dfPersonatHome,
                              "Siblings at School" = dfSiblingsatSch,
                              "Types of Houses" = dfTypesofHouses)
dfHouseholdData


#1b
#the data is about a Household occupants

summary(dfHouseholdData)

#c

#no, its 2.95

#d

oneand2 <- dfHouseholdData[1:2,]
oneand2

#e
third5and24 <- dfHouseholdData[c(3,5),c(2,4)]
third5and24

#f
types_houses <- dfHouseholdData[,6]
types_houses


#g

dfMaleFatherOcc <- dfHouseholdData[dfHouseholdData$Sex == 1 & dfHouseholdData$Fathers.Occupation == 1, c(2,3)]
dfMaleFatherOcc


#h

dfFemaleSiblings <- dfHouseholdData[dfHouseholdData$Sex == 2 & dfHouseholdData$Siblings.at.School >= 5, c(2,5) ]
dfFemaleSiblings




#2


dfofNum2 = data.frame(Ints=integer(),
                      Doubles=double(),
                      Characters=character(),
                      Logicals=logical(),
                      Factors=factor(),
                      stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(dfofNum2))

#it prints the structure of the dataframe


#3

df2Respondents <- c(1,2,3,4,5,6,7,8,9,10)
df2Sex <- c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male","Female", "Male")
df2FathersOcc <- c(1,2,3,3,1,2,2,3,1,3)
df2PersonatHome<- c(5,7,3,8,6,4,4,2,11,6)
df2SiblingsatSch <- c(2,3,0,5,2,3,1,2,6,2)
df2TypeofHouses <- c("Wood", "Congrete", "Congrete", "Wood", "Semi-congrete", "Semi-congrete", "Wood", "Semi-congrete", "Semi-congrete", "Congrete")

df2HouseholdData <- data.frame("Respondetns" = df2Respondents,
                               "Sex" = df2Sex,
                               "Fathers Occupation" = df2FathersOcc,
                               "Person at Home" = df2PersonatHome,
                               "Siblings at Schoo" = df2SiblingsatSch,
                               "Type of Houses" = df2TypeofHouses)
df2HouseholdData



write.csv(df2HouseholdData, file = "HouseholdData.csv")


#3a

csvHouseholdData <- read.csv(file = "HouseholdData.csv")
csvHouseholdData


#3b


csvHouseholdDataSex <- as.integer(factor(csvHouseholdData$Sex, levels = c("Male", "Female")))
csvHouseholdDataSex



#3c


csvHouseholdDataTypeofHouses <- as.integer(factor(csvHouseholdData$Type.of.Houses, levels = c("Wood", "Congrete","Semi-congrete")))

csvHouseholdDataTypeofHouses


#3d
#its already on int type
csvHouseholdData$Fathers.Occupation

csvHouseholdDataFathersOcc  <- factor(csvHouseholdData$Fathers.Occupation, levels = c(1,2,3), labels = c("Farmer", "Driver", "Others"))

csvHouseholdDataFathersOcc

#3e

csvHouseholdDataFemaleFatherOcc <- csvHouseholdData[csvHouseholdData$Sex == "Female" & csvHouseholdData$Fathers.Occupation == 2, c(3,4)]
csvHouseholdDataFemaleFatherOcc


#3f

csvHouseholdDataSibmorethan5 <- csvHouseholdData[csvHouseholdData$Siblings.at.Schoo >= 5 , c(2,6)]
csvHouseholdDataSibmorethan5


#4
#

mtxNNP <- cbind(
  c("2400+", "1500+", "1800+"),
  c("4250+", "2600+", "3200+"),
  c("3250+", "1900+", "2300+"),
  c("3300+", "2100+", "2600+"),
  c("2300+", "1400+", "1750+"),
  c("4100+", "2750+", "3300+")
)
                        
           

dimnames(mtxNNP) <- list(c("Negative", "Neutral", "Positive"), c("July 14, 2020", "July 15, 2020","July 17, 2020","July 18,2022","July 20, 2020","July 21, 2020"))


mtxNNP


# In contrast with the other sentiments, there were more negative sentiments on July 14. This could represent a sign that certain occurrences or themes that day attracted adverse reactions.


# All attitudes increased on July 15, with the negative sentiment reaching its maximum level. This may indicate that something occurred on that day to cause negative reactions.


# July 17 - the negative opinions persisted and were still relatively substantial in comparison to the neutral and supportive opinions.


#July 18 - negative feelings persisted and were relatively strong compared to the neutral and    positive sentiments.


# The lowest point for all attitudes occurred on July 20, however there were still more negative    feelings than the other days. This can mean that nothing occurred that day.

#July 21 - all reactions increased, with the negative mood reaching its highest level. This can also mean that something happened on that day that might have caused others to react negatively.


# We might conclude from this data that society's opinion is affected by outside factors and that it change over time.





```


