---
title: "RWorksheet_Quillo#4a"
author: "Carl"
date: "2023-10-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r WS4, echo = TRUE}
#1. The table shows the data about shoe size and height. Create a data frame.

#1. a
dfHouseholdData <- data.frame("Shoe size" =c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),
                              "Height" = c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0),
                              "Gender" = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M"))

dfHouseholdData

# 1. B.Create a subset by males and females with their corresponding shoe size and height.
# What its result? Show the R scripts.

subMaleShoeSize <- subset(dfHouseholdData, Gender == 'M')
subMaleShoeSize

subFemaleShoeSize <- subset(dfHouseholdData, Gender == 'F')
subFemaleShoeSize

#1.C Find the mean of shoe size and height of the respondents. Write the R scripts and its
# result.

shoeSizeandHeight <- mean(dfHouseholdData$Shoe.size & dfHouseholdData$Height)
shoeSizeandHeight
 
#1.D Is there a relationship between shoe size and height? Why?

# if the height is small the shoe size it also small


# 2 Construct character vector months to a factor with factor() and assign the result to
# factor_months_vector. Print out factor_months_vector and assert that R prints out
# the factor levels below the actual values.

months_vector <- c("March","April","January","November","January","September","October","September","November","August","January","November","November","February","May","August","July","December","August","August","September","November","February","April")
months_vector

factor_months_vector <- factor(months_vector)
factor_months_vector

#3 Then check the summary() of the months_vector and factor_months_vector. | Inter-
# pret the results of both vectors. Are they both equally useful in this case?

sumofmonths <- summary(months_vector)
sumofmonths

sumoffacmonths <- summary(factor_months_vector)
sumoffacmonths


# 4 Create a vector and factor

direction_vector <- c("East", "West", "West", "West", "West", "North", "North", "North")

direction_factor <- factor(direction_vector, levels = c("East", "West", "North"))

print(direction_factor)

#5

csvdata <- read.table(file = "import_match.csv", sep = ",", header = TRUE)
csvdata

#6a Create an R Program that allows the User to randomly select numbers from 1 to 50.
# Then display the chosen number. If the number is beyond the range of the selected choice,
# it will have to display a string “The number selected is beyond the range of 1 to 50”. If
#number 20 is inputted by the User, it will have to display “TRUE”, otherwise display the input number.

inputnum <- readline(paste("Eneter a number from 1 to 50"))

if(inputnum > 50){
  paste("You Enetered ", inputnum)
}else{
  paste("The number selected is beyond the range of 1 to 50")
}

# 7 Write a function that prints the minimum number of bills that must be paid, given the price of the snack.
#Input: Price of snack (a random number divisible by 50) Output: Minimum number of bills needed to purchase a snack.

priceofsnack <- as.numeric(readline(paste("Enter the price of the snacks: ")))

numofbills <- function(priceofsnack){
  
  minBills <- priceofsnack %/% 50
  paste("The minimum number of bills is:", minBills)
  
}


# 8a Create a dataframe from the above table. Write the R codes and its output.
dfstudents <- data.frame("Name" = c("Annie","Thea", "Steve","Hanna"),
                         "Grade 1" = c(85,65,75,95),
                         "Grade 2" = c(65,75,55,75),
                         "Grade 3" = c(85,90,80,100),
                         "Grade 4" = c(100,90,85,90))
dfstudents

#8b Without using the rowMean function, output the average score of students whose average math score over 90 points during the semester. write R code and its output.

test_averages <- rowSums(dfstudents[, -1]) / ncol(dfstudents[, -1])
test_averages

high_scorers <- dfstudents[test_averages >= 90, ]

if(nrow(high_scorers) > 0){
   paste(dfstudents$Name, "'s average grade this semester is", test_averages)
}else{
  paste("No student has an average math score over 90 points during the semester")
}


#8c Without using the mean function, output as follows for the tests in which the average score was less than 80 out of 4 tests.

avegrade1 <- sum(dfstudents$Grade.1) /4

avegrade2 <- sum(dfstudents$Grade.2) /4

avegrade3 <- sum(dfstudents$Grade.3) /4

avegrade4 <- sum(dfstudents$Grade.4) /4

test_averages  <- c(avegrade1, avegrade2, avegrade3, avegrade4)

difficult_tests <- which(test_averages < 80)

if (length(difficult_tests) > 0) {
  cat(paste("The grade", paste(difficult_tests, collapse = ", "), "test(s) were difficult.\n"))
} else {
  cat("No test was difficult.\n")
}

#8d Without using the max function, output as follows for students whose highest score for a semester exceeds 90 points.

df1strow <- dfstudents[1,2:5]
df2ndrow <- dfstudents[2,2:5]
df3rdrow <- dfstudents[3,2:5]
df4throw <- dfstudents[4,2:5]

if(df1strow[1] > 90){
  paste("Annie highest grade this semester is",df1strow[1],"")
}else if(df1strow[2] >90){
  paste("Annie highest grade this semester is",df1strow[2],"")
}else if(df1strow[3] >90){
  paste("Annie highest grade this semester is",df1strow[3],"")
}else if(df1strow[4] >90){
  paste("Annie highest grade this semester is",df1strow[4],"")
}else{
  paste("Annie has no grade that is higher than 90")
}

if(df2ndrow[1] > 90){
  paste("Thea highest grade this semester is",df2ndrow[1],"")
}else if(df2ndrow[2] >90){
  paste("Thea highest grade this semester is",df2ndrow[2],"")
}else if(df2ndrow[3] >90){
  paste("Thea highest grade this semester is",df2ndrow[3],"")
}else if(df2ndrow[4] >90){
  paste("Thea highest grade this semester is",df2ndrow[4],"")
}else{
  paste("Thea has no grade that is higher than 90")
}

if(df3rdrow[1] > 90){
  paste("Steve highest grade this semester is",df3rdrow[1],"")
}else if(df3rdrow[2] >90){
  paste("Steve highest grade this semester is",df3rdrow[2],"")
}else if(df3rdrow[3] >90){
  paste("Steve highest grade this semester is",df3rdrow[3],"")
}else if(df3rdrow[4] >90){
  paste("Steve highest grade this semester is",df1strow[4],"")
}else{
  paste("Steve has no grade that is higher than 90")
}


if(df4throw[1] > 90){
  paste("Hanna highest grade this semester is",df4throw[3],"")
}else if(df4throw[4] >90){
  paste("Hanna highest grade this semester is",df4throw[2],"")
}else if(df4throw[3] >90){
  paste("Hanna highest grade this semester is",df4throw[3],"")
}else if(df4throw[4] >90){
  paste("Hanna highest grade this semester is",df4throw[4],"")
}else{
  paste("Hanna has no grade that is higher than 90")
}





```
